/*! \file
    \brief Autogenerated enumerations (Umba Enum Gen)
 */

#pragma once


#include "marty_cpp/marty_enum.h"
#include "marty_cpp/marty_flag_ops.h"
#include "marty_cpp/marty_flags.h"

#include <exception>
#include <map>
#include <stdexcept>
#include <string>
#include <unordered_map>



namespace umba{
namespace tokenizer{
namespace ufsm{

//#!StateActions
enum class StateActions : std::uint32_t
{
    invalid     = (std::uint32_t)(-1) /*!<  */,
    none        = 0x0000 /*!<  */,
    enter       = 0x0001 /*!<  */,
    leave       = 0x0002 /*!<  */,
    selfEnter   = 0x0003 /*!<  */,
    selfLeave   = 0x0004 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_IS_FLAGS_FOR_NON_FLAGS_ENUM(StateActions)

MARTY_CPP_ENUM_CLASS_SERIALIZE_BEGIN( StateActions, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( StateActions::leave       , "Leave"     );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( StateActions::invalid     , "Invalid"   );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( StateActions::selfEnter   , "SelfEnter" );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( StateActions::none        , "None"      );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( StateActions::enter       , "Enter"     );
    MARTY_CPP_ENUM_CLASS_SERIALIZE_ITEM( StateActions::selfLeave   , "SelfLeave" );
MARTY_CPP_ENUM_CLASS_SERIALIZE_END( StateActions, std::map, 1 )

MARTY_CPP_ENUM_CLASS_DESERIALIZE_BEGIN( StateActions, std::map, 1 )
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::leave       , "leave"      );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::invalid     , "invalid"    );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::selfEnter   , "self-enter" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::selfEnter   , "self_enter" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::selfEnter   , "selfenter"  );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::none        , "none"       );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::enter       , "enter"      );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::selfLeave   , "self-leave" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::selfLeave   , "self_leave" );
    MARTY_CPP_ENUM_CLASS_DESERIALIZE_ITEM( StateActions::selfLeave   , "selfleave"  );
MARTY_CPP_ENUM_CLASS_DESERIALIZE_END( StateActions, std::map, 1 )


//#!ActionFlags
enum class ActionFlags : std::uint32_t
{
    invalid     = (std::uint32_t)(-1) /*!<  */,
    none        = 0x0000 /*!<  */,
    external    = 0x0001 /*!<  */,
    generates   = 0x0002 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_FLAGS(ActionFlags)

MARTY_CPP_ENUM_FLAGS_SERIALIZE_BEGIN( ActionFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( ActionFlags::invalid     , "Invalid"   );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( ActionFlags::generates   , "Generates" );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( ActionFlags::none        , "None"      );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( ActionFlags::external    , "External"  );
MARTY_CPP_ENUM_FLAGS_SERIALIZE_END( ActionFlags, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_BEGIN( ActionFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ActionFlags::invalid     , "invalid"   );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ActionFlags::generates   , "generates" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ActionFlags::none        , "none"      );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ActionFlags::external    , "external"  );
MARTY_CPP_ENUM_FLAGS_DESERIALIZE_END( ActionFlags, std::map, 1 )


//#!EventFlags
enum class EventFlags : std::uint32_t
{
    invalid     = (std::uint32_t)(-1) /*!<  */,
    none        = 0x0000 /*!<  */,
    external    = 0x0001 /*!<  */,
    generated   = 0x0002 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_FLAGS(EventFlags)

MARTY_CPP_ENUM_FLAGS_SERIALIZE_BEGIN( EventFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( EventFlags::invalid     , "Invalid"   );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( EventFlags::none        , "None"      );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( EventFlags::generated   , "Generated" );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( EventFlags::external    , "External"  );
MARTY_CPP_ENUM_FLAGS_SERIALIZE_END( EventFlags, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_BEGIN( EventFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( EventFlags::invalid     , "invalid"   );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( EventFlags::none        , "none"      );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( EventFlags::generated   , "generated" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( EventFlags::external    , "external"  );
MARTY_CPP_ENUM_FLAGS_DESERIALIZE_END( EventFlags, std::map, 1 )


//#!InheritanceOverrideFlags
enum class InheritanceOverrideFlags : std::uint32_t
{
    invalid       = (std::uint32_t)(-1) /*!<  */,
    none          = 0x0000 /*!<  */,
    events        = 0x0001 /*!<  */,
    actions       = 0x0002 /*!<  */,
    predicates    = 0x0004 /*!<  */,
    states        = 0x0008 /*!<  */,
    transitions   = 0x0010 /*!<  */,
    all           = events|actions|predicates|states|transitions /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_FLAGS(InheritanceOverrideFlags)

MARTY_CPP_ENUM_FLAGS_SERIALIZE_BEGIN( InheritanceOverrideFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( InheritanceOverrideFlags::invalid       , "Invalid"     );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( InheritanceOverrideFlags::transitions   , "Transitions" );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( InheritanceOverrideFlags::none          , "None"        );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( InheritanceOverrideFlags::all           , "All"         );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( InheritanceOverrideFlags::actions       , "Actions"     );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( InheritanceOverrideFlags::events        , "Events"      );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( InheritanceOverrideFlags::states        , "States"      );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( InheritanceOverrideFlags::predicates    , "Predicates"  );
MARTY_CPP_ENUM_FLAGS_SERIALIZE_END( InheritanceOverrideFlags, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_BEGIN( InheritanceOverrideFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( InheritanceOverrideFlags::invalid       , "invalid"     );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( InheritanceOverrideFlags::transitions   , "transitions" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( InheritanceOverrideFlags::none          , "none"        );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( InheritanceOverrideFlags::all           , "all"         );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( InheritanceOverrideFlags::actions       , "actions"     );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( InheritanceOverrideFlags::events        , "events"      );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( InheritanceOverrideFlags::states        , "states"      );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( InheritanceOverrideFlags::predicates    , "predicates"  );
MARTY_CPP_ENUM_FLAGS_DESERIALIZE_END( InheritanceOverrideFlags, std::map, 1 )


//#!StateFlags
enum class StateFlags : std::uint32_t
{
    invalid   = (std::uint32_t)(-1) /*!<  */,
    none      = 0x0000 /*!<  */,
    initial   = 0x0001 /*!<  */,
    final     = 0x0002 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_FLAGS(StateFlags)

MARTY_CPP_ENUM_FLAGS_SERIALIZE_BEGIN( StateFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( StateFlags::invalid   , "Invalid" );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( StateFlags::initial   , "Initial" );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( StateFlags::none      , "None"    );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( StateFlags::final     , "Final"   );
MARTY_CPP_ENUM_FLAGS_SERIALIZE_END( StateFlags, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_BEGIN( StateFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( StateFlags::invalid   , "invalid" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( StateFlags::initial   , "initial" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( StateFlags::none      , "none"    );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( StateFlags::final     , "final"   );
MARTY_CPP_ENUM_FLAGS_DESERIALIZE_END( StateFlags, std::map, 1 )

} // namespace ufsm
} // namespace tokenizer
} // namespace umba

