/*! \file
    \brief Autogenerated enumerations (Umba Enum Gen)
 */

#pragma once


#include "marty_cpp/marty_enum.h"
#include "marty_cpp/marty_flag_ops.h"
#include "marty_cpp/marty_flags.h"

#include <exception>
#include <map>
#include <stdexcept>
#include <string>
#include <unordered_map>



namespace umba{
namespace tokenizer{

//#!ParserWaitForTokenFlags
enum class ParserWaitForTokenFlags
{
    stopOnLinefeed           = 0x0001 /*!<  */,
    stopOnComment            = 0x0002 /*!<  */,
    stopOnMultilineComment   = 0x0004 /*!<  */

}; // enum 
//#!

MARTY_CPP_MAKE_ENUM_FLAGS(ParserWaitForTokenFlags)

MARTY_CPP_ENUM_FLAGS_SERIALIZE_BEGIN( ParserWaitForTokenFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnLinefeed          , "StopOnLinefeed"         );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnComment           , "StopOnComment"          );
    MARTY_CPP_ENUM_FLAGS_SERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnMultilineComment  , "StopOnMultilineComment" );
MARTY_CPP_ENUM_FLAGS_SERIALIZE_END( ParserWaitForTokenFlags, std::map, 1 )

MARTY_CPP_ENUM_FLAGS_DESERIALIZE_BEGIN( ParserWaitForTokenFlags, std::map, 1 )
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnLinefeed          , "stop-on-linefeed"          );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnLinefeed          , "stop_on_linefeed"          );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnLinefeed          , "stoponlinefeed"            );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnComment           , "stop-on-comment"           );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnComment           , "stop_on_comment"           );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnComment           , "stoponcomment"             );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnMultilineComment  , "stop-on-multiline-comment" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnMultilineComment  , "stop_on_multiline_comment" );
    MARTY_CPP_ENUM_FLAGS_DESERIALIZE_ITEM( ParserWaitForTokenFlags::stopOnMultilineComment  , "stoponmultilinecomment"    );
MARTY_CPP_ENUM_FLAGS_DESERIALIZE_END( ParserWaitForTokenFlags, std::map, 1 )

} // namespace tokenizer
} // namespace umba

